version: '3'

services:
  bd:
    build:
      context: ./backend/bd
      dockerfile: Dockerfile
#    image: ruvika07/webscrapping:v1
    container_name: bd_app

  datos:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
#    image: ruvika07/webscrapping:v1
    container_name: datos

  api_backend:
    build:
      context: ./backend/srp
      dockerfile: Dockerfile
  #  image: ruvika07/backend:v1
    container_name: api_backend
    ports:
      - '5000:5000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
#    image: ruvika07/frontend:v1
    container_name: frontend
    ports:
      - '8501:8501'
    depends_on: 
      - api_backend